#!/usr/bin/env python3
"""
Workflow Executor - Stage-by-Stage DAG Execution Engine

Executes workflow DAGs generated by WorkflowGenerator using ADK primitives.

Key Features:
    - Stage-by-stage execution (each stage completes before next starts)
    - Context management (pass data between stages)
    - Timeout support per stage
    - Comprehensive error handling
    - Partial success handling (some nodes can fail)
    - Detailed logging for debugging

Execution Model:
    1. Build executable workflow from config (attach executors to nodes)
    2. Execute flow stage by stage: flow = [[stage1_nodes], [stage2_nodes], ...]
    3. Pass results from one stage as input to next stage
    4. Return final stage result

Usage:
    executor = WorkflowExecutor()
    result = executor.execute_workflow(
        workflow=workflow_config,
        input_data={"query": "...", "location": "..."},
        context={"discovered_agents": {...}, ...}
    )
"""

from concurrent.futures import ThreadPoolExecutor, as_completed
import os
import re
from typing import Any

from lib.logger import get_logger

from .adk_primitives import ADKPrimitives
from .workflow_models import ADKNode, ExecutableWorkflow, NodeType, WorkflowConfig


class WorkflowExecutor:
    """
    Execute workflow DAGs stage by stage.

    Manages context, data flow, and error handling during workflow execution.
    """

    def __init__(self, default_timeout: int = 90):
        """
        Initialize WorkflowExecutor.

        Args:
            default_timeout: Default timeout for entire workflow in seconds
        """
        self.default_timeout = default_timeout
        self.logger = get_logger(context={"component": "WorkflowExecutor"})

        self.logger.info("WorkflowExecutor initialized")

    def execute_workflow(
        self,
        workflow: ExecutableWorkflow,
        input_data: dict[str, Any],
        context: dict[str, Any],
    ) -> Any:
        """
        Execute workflow following flow stages.

        Args:
            workflow: ExecutableWorkflow with ADK nodes
            input_data: Initial input data (query, location, etc.)
            context: Execution context (discovered agents, bedrock model, etc.)

        Returns:
            Final workflow result (from last stage)

        Raises:
            RuntimeError: If workflow execution fails critically
        """
        self.logger.debug(
            "Starting workflow execution",
        )

        try:
            # Initialize execution state
            current_data = input_data
            stage_results_history = []
            accumulated_stage_results = {}  # Flat dict of all node results

            # Execute each stage
            for stage_idx in range(workflow.total_stages()):
                # 🎯 MILESTONE: Visual stage marker for workshop learners
                self.logger.info("=" * 70)
                self.logger.info(
                    f"🎯 STAGE {stage_idx + 1}/{workflow.total_stages()} - Executing workflow stage"
                )
                self.logger.info("=" * 70)

                # Get nodes for this stage
                stage_nodes = workflow.get_stage_nodes(stage_idx)
                stage_node_ids = workflow.flow[stage_idx]

                # Update context with accumulated stage history for data mapping
                context["stage_history"] = accumulated_stage_results

                # Execute stage
                stage_results = self._execute_stage(
                    stage_nodes=stage_nodes,
                    stage_node_ids=stage_node_ids,
                    input_data=current_data,
                    context=context,
                    stage_idx=stage_idx,
                )

                # Store stage results
                stage_results_history.append(stage_results)

                # Accumulate all stage results into flat dict for JSONPath access
                accumulated_stage_results.update(stage_results)

                # 🧹 PRUNE: Remove consumed stages not needed by future stages
                # Check environment variable for debug override
                keep_full_history = (
                    os.environ.get("KEEP_FULL_STAGE_HISTORY", "false").lower() == "true"
                )

                if not keep_full_history and stage_idx < workflow.total_stages() - 1:
                    # Get all future stages
                    future_stages = []
                    for future_idx in range(stage_idx + 1, workflow.total_stages()):
                        future_stages.extend(workflow.get_stage_nodes(future_idx))

                    # Find which node_ids are referenced by future stages
                    referenced_nodes = set()
                    for future_node in future_stages:
                        # Check input_mapping for explicit dependencies
                        if (
                            hasattr(future_node, "input_mapping")
                            and future_node.input_mapping
                        ):
                            # Parse JSONPath expressions in input_mapping
                            for path_expr in future_node.input_mapping.values():
                                if isinstance(path_expr, str) and path_expr.startswith(
                                    "$."
                                ):
                                    # Extract node_id from JSONPath (e.g., "$.location_loader.locations" -> "location_loader")
                                    parts = path_expr[2:].split(".", 1)
                                    if parts:
                                        referenced_nodes.add(parts[0])

                        # Check wait_for for synthesis dependencies (implicit dependencies)
                        if (
                            future_node.type == NodeType.JOINER
                            and future_node.config.get("wait_for")
                        ):
                            # Joiner's wait_for list explicitly declares which nodes are needed for synthesis
                            wait_for_nodes = future_node.config["wait_for"]
                            referenced_nodes.update(wait_for_nodes)
                            self.logger.debug(
                                f"Preserving wait_for nodes for joiner '{future_node.id}': {wait_for_nodes}"
                            )

                    # Remove nodes that aren't referenced by any future stage
                    pruned_nodes = []
                    for node_id in list(accumulated_stage_results.keys()):
                        if node_id not in referenced_nodes:
                            # Check if this node is from a completed stage (not current)
                            if node_id not in stage_results:
                                del accumulated_stage_results[node_id]
                                pruned_nodes.append(node_id)

                    if pruned_nodes:
                        self.logger.info(
                            f"🧹 Pruned {len(pruned_nodes)} node(s) from stage_history: {pruned_nodes}"
                        )

                # 🧹 PRUNE: Remove Joiner input data after Joiner processes it
                # This prevents raw agent data from being retained after aggregation
                stage_nodes = workflow.get_stage_nodes(stage_idx)
                if len(stage_nodes) == 1:
                    stage_node = stage_nodes[0]
                    if stage_node.type == NodeType.JOINER and stage_node.config.get(
                        "wait_for"
                    ):
                        # Joiner has processed its inputs - prune them
                        wait_for_ids = stage_node.config["wait_for"]
                        pruned_count = 0

                        for node_id in wait_for_ids:
                            if node_id in accumulated_stage_results:
                                del accumulated_stage_results[node_id]
                                pruned_count += 1

                        if pruned_count > 0:
                            self.logger.info(
                                f"🧹 Pruned {pruned_count} Joiner input node(s) after aggregation: {wait_for_ids}"
                            )

                # 🔍 DIAGNOSTIC: Log accumulated stage_history structure
                stage_history_preview = {}
                for node_id, node_result in accumulated_stage_results.items():
                    if isinstance(node_result, dict):
                        # Preview dict structure
                        preview_keys = {}
                        for key, value in node_result.items():
                            if isinstance(value, list):
                                preview_keys[key] = f"<list with {len(value)} items>"
                            elif isinstance(value, dict):
                                preview_keys[key] = f"<dict with {len(value)} keys>"
                            else:
                                preview_keys[key] = f"<{type(value).__name__}>"
                        stage_history_preview[node_id] = preview_keys
                    elif isinstance(node_result, list):
                        stage_history_preview[node_id] = (
                            f"<list with {len(node_result)} items>"
                        )
                    else:
                        stage_history_preview[node_id] = (
                            f"<{type(node_result).__name__}>"
                        )

                self.logger.debug(
                    f"📊 Stage {stage_idx + 1} accumulated results",
                )

                # Update current_data for next stage
                # If single node in stage, use its result directly
                # If multiple nodes, pass dict of results
                if len(stage_results) == 1:
                    current_data = list(stage_results.values())[0]
                else:
                    current_data = stage_results

                # 🎯 MILESTONE: Stage completion marker
                self.logger.info(
                    f"✓ Stage {stage_idx + 1} completed",
                )
                self.logger.info("")  # Blank line for visual separation

            # Return final result - intelligently select what synthesis needs
            # Check if we have multiple stages to potentially merge
            if len(stage_results_history) > 1:
                # Check if final stage is a joiner with wait_for list
                final_stage_nodes = workflow.get_stage_nodes(
                    workflow.total_stages() - 1
                )

                if final_stage_nodes and len(final_stage_nodes) == 1:
                    final_node = final_stage_nodes[0]

                    if final_node.type == NodeType.JOINER and final_node.config.get(
                        "wait_for"
                    ):
                        # Return the Joiner's OUTPUT, not its INPUT
                        # This prevents double synthesis when Joiner has already processed the data
                        joiner_result = accumulated_stage_results.get(final_node.id)

                        if joiner_result is not None:
                            self.logger.info(
                                f"📤 WORKFLOW RETURN - Returning Joiner output from {final_node.id}"
                            )
                            # Return in dict format for consistent interface with orchestrator
                            return {final_node.id: joiner_result}
                        else:
                            # Fallback: return wait_for nodes if Joiner output missing
                            wait_for_ids = final_node.config["wait_for"]
                            self.logger.warning(
                                f"Joiner {final_node.id} output not found in accumulated_stage_results, "
                                f"falling back to wait_for nodes: {wait_for_ids}"
                            )
                            synthesis_data = {
                                node_id: result
                                for node_id, result in accumulated_stage_results.items()
                                if node_id in wait_for_ids
                            }
                            return synthesis_data

                # Check if final stage has multiple nodes (parallel)
                final_stage = stage_results_history[-1]
                if len(final_stage) > 1:
                    # Final stage is parallel - return all final stage results
                    # This ensures parallel workflows get all results for synthesis to combine
                    self.logger.debug(
                        f"Returning final parallel stage results for synthesis: {list(final_stage.keys())}"
                    )

                    # 🔍 DIAGNOSTIC: Log what's being returned to synthesizer
                    self.logger.info(
                        f"📤 WORKFLOW RETURN - Returning to synthesizer: keys={list(final_stage.keys())}"
                    )

                    return final_stage

                # Final stage is sequential (single node) - return ONLY final stage
                # This prevents sending intermediate filtered data to synthesis
                self.logger.debug(
                    f"Returning final sequential stage result for synthesis: {list(final_stage.keys())}"
                )

                # 🔍 DIAGNOSTIC: Log what's being returned to synthesizer
                self.logger.info(
                    f"📤 WORKFLOW RETURN - Returning to synthesizer: keys={list(final_stage.keys())}"
                )

                return final_stage
            else:
                # Single stage workflow - return current data
                self.logger.debug("Workflow execution completed successfully")
                return current_data

        except Exception as e:
            self.logger.error(
                "Workflow execution failed",
                exc_info=True,
            )
            raise RuntimeError(f"Workflow execution failed: {e}")

    def _execute_stage(
        self,
        stage_nodes: list[ADKNode],
        stage_node_ids: list[str],
        input_data: Any,
        context: dict[str, Any],
        stage_idx: int,
    ) -> dict[str, Any]:
        """
        Execute all nodes in a stage.

        Nodes in same stage can be executed in parallel (if they're agent_calls or routers).
        Other nodes (conditions, joiners) typically execute sequentially.

        Args:
            stage_nodes: List of ADKNode objects to execute
            stage_node_ids: List of node IDs (for ordering)
            input_data: Input data for this stage
            context: Execution context
            stage_idx: Stage index (for logging)

        Returns:
            Dictionary mapping node_id -> result
        """
        results = {}

        # Determine if we can parallelize this stage
        # We can parallelize if all nodes are agent_call or router types
        can_parallelize = all(
            node.type in [NodeType.AGENT_CALL, NodeType.ROUTER] for node in stage_nodes
        )

        if can_parallelize and len(stage_nodes) > 1:
            # Parallel execution
            self.logger.debug(
                f"Stage {stage_idx}: Executing {len(stage_nodes)} nodes in parallel"
            )
            results = self._execute_stage_parallel(stage_nodes, input_data, context)
        else:
            # Sequential execution
            self.logger.debug(
                f"Stage {stage_idx}: Executing {len(stage_nodes)} nodes sequentially"
            )
            results = self._execute_stage_sequential(stage_nodes, input_data, context)

        return results

    def _execute_stage_parallel(
        self, stage_nodes: list[ADKNode], input_data: Any, context: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute stage nodes in parallel using ThreadPoolExecutor.

        Args:
            stage_nodes: Nodes to execute
            input_data: Input data for nodes
            context: Execution context

        Returns:
            Dictionary of node_id -> result
        """
        results = {}

        with ThreadPoolExecutor(max_workers=len(stage_nodes)) as pool:
            # Submit all nodes
            future_to_node = {}
            for node in stage_nodes:
                future = pool.submit(self._execute_node, node, input_data, context)
                future_to_node[future] = node

            # Collect results with timeout
            for future in as_completed(future_to_node, timeout=self.default_timeout):
                node = future_to_node[future]
                try:
                    result = future.result()
                    results[node.id] = result

                    # 🔍 DIAGNOSTIC: Log agent response details (DEBUG level)
                    self.logger.debug(
                        "🔍 DIAGNOSTIC - Node completed",
                    )
                    self.logger.debug(f"Node {node.id} completed successfully")
                except Exception as e:
                    self.logger.error(f"Node {node.id} failed")
                    results[node.id] = {"error": str(e), "node_id": node.id}

        return results

    def _execute_stage_sequential(
        self, stage_nodes: list[ADKNode], input_data: Any, context: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Execute stage nodes sequentially.

        Args:
            stage_nodes: Nodes to execute
            input_data: Input data for nodes
            context: Execution context

        Returns:
            Dictionary of node_id -> result
        """
        results = {}

        for node in stage_nodes:
            try:
                result = self._execute_node(node, input_data, context)
                results[node.id] = result
                self.logger.debug(f"Node {node.id} completed successfully")

                # For sequential execution, update input_data with latest result
                # This allows nodes to build on each other's results
                input_data = result

            except Exception as e:
                self.logger.error(f"Node {node.id} failed")
                results[node.id] = {"error": str(e), "node_id": node.id}
                # Continue with next node even if this one failed

        return results

    def _execute_node(
        self, node: ADKNode, input_data: Any, context: dict[str, Any]
    ) -> Any:
        """
        Execute a single workflow node.

        Args:
            node: ADKNode to execute
            input_data: Input data for node
            context: Execution context

        Returns:
            Node execution result
        """
        self.logger.debug(
            f"Executing node: {node.id}",
        )

        if node.execute is None:
            self.logger.error(f"Node {node.id} has no executor function")
            return {"error": f"Node {node.id} cannot be executed (no executor)"}

        try:
            # For Joiner nodes, pass stage_history instead of input_data
            # so wait_for filtering can find agent IDs
            if node.type == NodeType.JOINER:
                stage_history = context.get("stage_history", {})
                result = node.execute(context, stage_history)
            else:
                result = node.execute(context, input_data)
            return result

        except Exception:
            self.logger.error(
                f"Node {node.id} execution failed",
            )
            raise

    def _is_error(self, result: Any) -> bool:
        """
        Check if result contains an error.

        Args:
            result: Result to check

        Returns:
            True if result indicates error, False otherwise
        """
        if isinstance(result, dict) and "error" in result:
            return True
        return False

    def _validate_input_mappings(self, workflow_config: WorkflowConfig) -> list[str]:
        """
        Validate all input_mapping configurations in the workflow.

        Checks:
        1. Referenced node IDs exist in workflow
        2. JSONPath expressions have valid syntax
        3. Dependencies are properly ordered in flow

        Args:
            workflow_config: Workflow configuration to validate

        Returns:
            List of validation warning messages (empty if all valid)
        """
        warnings = []

        # Build node ID set for validation
        all_node_ids = {node["id"] for node in workflow_config.nodes}

        # Build stage index for each node (for ordering validation)
        node_to_stage = {}
        for stage_idx, stage_nodes in enumerate(workflow_config.flow):
            for node_id in stage_nodes:
                node_to_stage[node_id] = stage_idx

        # Validate each node's input_mapping
        for node_config in workflow_config.nodes:
            node_id = node_config["id"]
            input_mapping = node_config.get("input_mapping")

            if not input_mapping:
                continue  # No mapping to validate

            if not isinstance(input_mapping, dict):
                warnings.append(
                    f"Node '{node_id}': input_mapping must be a dictionary, got {type(input_mapping)}"
                )
                continue

            # Validate each mapping value
            for target_field, value in input_mapping.items():
                # Allow strings, lists, dicts, numbers, booleans, None
                # These are all valid JSON-serializable types that can be passed to agents
                if not isinstance(
                    value, (str, list, dict, int, float, bool, type(None))
                ):
                    warnings.append(
                        f"Node '{node_id}': Value for field '{target_field}' has invalid type {type(value).__name__}"
                    )
                    continue

                # Check if this is a JSONPath expression (only strings can be JSONPath)
                if isinstance(value, str) and value.startswith("$."):
                    # This is a JSONPath expression - validate it further below
                    pass
                else:
                    # This is a LITERAL VALUE (e.g., "Pike Place", ["vegan"], {"key": "value"})
                    # Literal values are valid - they will be passed directly to the agent
                    # No further validation needed for literals
                    continue

                # This is a JSONPath expression - validate it
                # Extract referenced node ID from JSONPath (e.g., "$.events_call.events" -> "events_call")
                # Pattern: $.node_id.rest.of.path or $.node_id[0].path
                match = re.match(r"\$\.([a-zA-Z_][a-zA-Z0-9_]*)", value)
                if not match:
                    warnings.append(
                        f"Node '{node_id}': Invalid JSONPath syntax '{value}' "
                        f"(for field '{target_field}')"
                    )
                    continue

                referenced_node_id = match.group(1)

                # Check if referenced node exists
                if referenced_node_id not in all_node_ids:
                    warnings.append(
                        f"Node '{node_id}': input_mapping references non-existent node '{referenced_node_id}' "
                        f"in path '{value}' (for field '{target_field}')"
                    )
                    continue

                # Check stage ordering (referenced node should be in earlier stage)
                current_stage = node_to_stage.get(node_id)
                referenced_stage = node_to_stage.get(referenced_node_id)

                if current_stage is not None and referenced_stage is not None:
                    if referenced_stage >= current_stage:
                        warnings.append(
                            f"Node '{node_id}' (stage {current_stage}) references node '{referenced_node_id}' "
                            f"(stage {referenced_stage}), but dependencies must be from earlier stages"
                        )

        return warnings

    def build_executable_workflow(
        self, workflow_config: WorkflowConfig, context: dict[str, Any]
    ) -> ExecutableWorkflow:
        """
        Build executable workflow from configuration.

        Converts workflow config nodes into ADKNode objects with executor functions.

        Args:
            workflow_config: Workflow configuration from WorkflowGenerator
            context: Execution context (needed for some primitives)

        Returns:
            ExecutableWorkflow with nodes ready to execute
        """
        self.logger.debug(
            "Building executable workflow",
        )

        # Validate input_mapping configurations
        validation_warnings = self._validate_input_mappings(workflow_config)
        if validation_warnings:
            self.logger.warning(
                "Input mapping validation found issues",
            )
            # Log each warning individually for visibility
            for warning in validation_warnings:
                self.logger.warning(f"Input mapping issue: {warning}")
        else:
            self.logger.debug("✓ Input mapping validation passed")

        nodes = {}

        for node_config in workflow_config.nodes:
            node_id = node_config["id"]
            node_type = NodeType(node_config["type"])

            # Create executor based on node type
            executor = self._create_executor(node_type, node_config)

            # Create ADK node
            adk_node = ADKNode(
                id=node_id, type=node_type, config=node_config, execute=executor
            )

            nodes[node_id] = adk_node
            self.logger.debug(f"Built node: {node_id}")

        # Create executable workflow
        executable = ExecutableWorkflow(
            nodes=nodes,
            flow=workflow_config.flow,
            pattern=workflow_config.pattern,
            metadata=workflow_config.metadata,
        )

        self.logger.debug(
            "Executable workflow built successfully",
        )

        return executable

    def _create_executor(
        self, node_type: NodeType, node_config: dict[str, Any]
    ) -> callable:
        """
        Create executor function for node based on its type.

        Args:
            node_type: Type of node
            node_config: Node configuration

        Returns:
            Executor function

        Raises:
            ValueError: If node type is unknown or config is invalid
        """
        if node_type == NodeType.ROUTER:
            # Build routing rules from config
            rules = self._build_routing_rules(node_config)
            parallel = node_config.get("parallel", False)
            timeout = node_config.get("timeout")

            return ADKPrimitives.router(rules=rules, parallel=parallel, timeout=timeout)

        elif node_type == NodeType.JOINER:
            strategy = node_config.get("strategy", "merge")
            wait_for = node_config.get("wait_for")
            timeout = node_config.get("timeout")

            return ADKPrimitives.joiner(
                strategy=strategy, wait_for=wait_for, timeout=timeout
            )

        elif node_type == NodeType.AGENT_CALL:
            agent_id = node_config.get("agent_id")
            if not agent_id:
                raise ValueError(
                    f"agent_call node {node_config['id']} missing agent_id"
                )

            tool_name = node_config.get("tool_name")
            timeout = node_config.get("timeout")
            input_mapping = node_config.get("input_mapping")

            return ADKPrimitives.agent_call(
                agent_id=agent_id,
                tool_name=tool_name,
                timeout=timeout,
                input_mapping=input_mapping,
            )

        elif node_type == NodeType.CONDITION:
            expression = node_config.get("expression")
            true_branch = node_config.get("true_branch")
            false_branch = node_config.get("false_branch")

            if not expression:
                raise ValueError(
                    f"condition node {node_config['id']} missing expression"
                )
            if not true_branch:
                raise ValueError(
                    f"condition node {node_config['id']} missing true_branch"
                )

            return ADKPrimitives.condition(
                expression=expression,
                true_branch=true_branch,
                false_branch=false_branch,
            )

        else:
            raise ValueError(f"Unknown node type: {node_type}")

    def _build_routing_rules(self, node_config: dict[str, Any]) -> list[dict[str, Any]]:
        """
        Build routing rules from node configuration.

        Args:
            node_config: Router node configuration

        Returns:
            List of routing rules for ADKPrimitives.router()
        """
        rules = []

        # Check if rules are explicitly provided
        if "rules" in node_config:
            return node_config["rules"]

        # Check if targets are provided (shorthand)
        if "targets" in node_config:
            for target in node_config["targets"]:
                rules.append({"target": target})

        return rules

    @staticmethod
    def _summarize_structure(data: Any) -> str:
        """
        Summarize data structure for diagnostic logging.

        Args:
            data: Data to summarize

        Returns:
            String describing structure (e.g., "list[30]", "dict[5 keys]")
        """
        if isinstance(data, dict):
            summary = {}
            for k, v in data.items():
                if isinstance(v, list):
                    summary[k] = f"list[{len(v)}]"
                elif isinstance(v, dict):
                    summary[k] = f"dict[{len(v)} keys]"
                else:
                    summary[k] = type(v).__name__
            return str(summary)
        elif isinstance(data, list):
            return f"list[{len(data)}]"
        else:
            return type(data).__name__
